config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :home do 
    collection do
      get "submit"
      get "successful"
      get "performance"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote
  include Mongoid::Document
	include Mongoid::Timestamps

  field :text
  field :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'uri'
require 'net/http'
class HomeController < ApplicationController
  def index
    @quote = Quote.all.sample
  end

  def submit
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(params.require(:quote).permit(:author, :text))
    redirect_to :successful_home_index
  end

  def performance

    uri = URI.parse("https://api.rapidmock.com/mocks/89mEw")
    requestLength = 2000  # You should replace this with the actual value

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(uri.path)
    request['Cache-Control'] = 'no-cache'
    request['x-rapidmock-delay'] = requestLength

    response = http.request(request)
  end

  def successful
  end

  def testapi
    render :json => {
      "name" => "Harry Bomrah",
      "age" => 30
  }.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_menu.html.erb
<nav>
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/home/submit">New</a></li>
    <li><a href="/home/performance">Performance</a></li>
  </ul>
</nav>

app/views/home/index.html.erb
<div >
  <%= render partial: 'menu' %>
  <div class="quote">
    <quote><i><%= @quote.text %></i></quote>
    <hr />
    <div class="back">
      <div class="name"><%= @quote.author %></div>
    </div>
  </div>
</div>

app/views/home/performance.html.erb
<div>
  <%= render partial: 'menu' %>
  <div class="quote">
    <div>Performance delay</div>
  </div>
</div>

app/views/home/submit.html.erb
<div>
  <%= render partial: 'menu' %>
  <div class="submit">
    <h3>Submit a Quote</h3>
    <div class="form">
      <%= form_with model: @quote, url: home_index_path, method: "post" do |form| %>
        <div class="field">
          <span><%= form.label :author, "Author" %></span>
          <%= form.text_field :author %>
        </div>
        <div class="field">
          <span><%= form.label :text, "Quote" %></span>
          <%= form.text_area :text, size: "60x10" %>
        </div>
        <div class="field">
          <%= form.submit "Submit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/successful.html.erb
<div>
  <%= render partial: 'menu' %>
  <div class="quote">
    <div>Quote submited successfully!!!</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodegiantDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="background">
    <%= yield %>
  </body>
</html>